kind: pipeline
type: docker
name: helmsman

platform:
  os: linux
  arch: arm64

environment:
  EXP: 2032-06-25T17:31:23Z

steps:

  - name: notify_slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: deploys
      icon_url: https://www.pngkit.com/png/full/92-920674_drone-logo-png-transparent-drone-ci-logo.png
      template: >
        {{#success build.status}}
          build {{build.number}} status: *{{build.status}}*
          build link: {{build.link}}
          build author: {{build.author}}
          build ref: {{build.ref}}
          build event: {{build.event}}
          build commit: {{build.commit}}
          build branch: {{build.branch}}
          build deploy: {{build.deployTo}}
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    environment:
      SLACK_HOOK:
        from_secret: slackhook_token
    when:
      status:
      - failure
      - success

  - name: security_scanning
    image: tenable/terrascan
    pull: if-not-exists
    privileged: false
    detach: false
    failure: ignore
    commands:
      - terrascan scan -v -i helm -d charts
    when:
      status:
        - "success"
      trigger:
        branch:
          - "CU-*"
    depends_on:
      - "notify_slack"

  - name: helm_lint
    image: praqma/helmsman
    pull: if-not-exists
    privileged: false
    detach: false
    commands:
      - echo $KUBECONFIG | base64 -d > config
      - chmod 600 config
      - export KUBECONFIG=config
      - export CONTEXT=$(kubectl config current-context)
      - export K8SCLUSTER=$CONTEXT
      - kubectl get nodes -owide
      - time helmsman -e variables.env -f k8s_common.yaml -f k8s_general.yaml -verbose -skip-validation -no-banner
    environment:
      KUBECONFIG:
        from_secret: kubeconfig
    when:
      status:
        - "success"
      trigger:
        branch:
          - "CU-*"
    depends_on:
      - "security_scanning"

  - name: helm_deploy
    image: praqma/helmsman
    pull: if-not-exists
    privileged: false
    detach: false
    commands:
      - apk add step-cli curl openssl
      - curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh
      - echo $KUBECONFIG | base64 -d > config
      - chmod 600 config
      - export KUBECONFIG=config
      - export CONTEXT=$(kubectl config current-context)
      - export K8SCLUSTER=$CONTEXT
      - kubectl get nodes -owide
      - time helmsman -e variables.env -f k8s_common.yaml -f k8s_general.yaml -verbose -apply -no-banner
    environment:
      KUBECONFIG:
        from_secret: kubeconfig
    when:
      status:
        - "success"
      branch: 
        - "master"
      event:
        - push
        - promote
      target:
        - production
    depends_on:
      - "helm_lint"

trigger:
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback
