kind: pipeline
type: docker
name: helmsman

platform:
  os: linux
  arch: arm64

environment:
  K8SCLUSTER: oromis
  CONFIG: kubeconfigs
  EXP: 2032-06-25T17:31:23Z

steps:

  - name: security_scanning
    image: tenable/terrascan
    pull: if-not-exists
    privileged: false
    detach: false
    failure: ignore
    commands:
      - terrascan scan -v -i helm -d charts
    when:
      status:
        - "success"
      trigger:
        branch:
          - "CU-*"

  - name: helm_lint
    image: praqma/helmsman
    pull: if-not-exists
    privileged: false
    detach: false
    commands:
      - export KUBECONFIG=$$CONFIG/$$K8SCLUSTER.yaml
      - chmod 600 $KUBECONFIG
      - kubectl get nodes
      - time helmsman -e variables.env -f k8s_common.yaml -f k8s_general.yaml -verbose -skip-validation
    when:
      status:
        - "success"
      trigger:
        branch:
          - "CU-*"
    depends_on:
      - "security_scanning"

  - name: helm_deploy
    image: praqma/helmsman
    pull: if-not-exists
    privileged: false
    detach: false
    commands:
      - apk add step-cli curl openssl
      - curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh
      - export KUBECONFIG=$$CONFIG/$$K8SCLUSTER.yaml 
      - chmod 600 $KUBECONFIG
      - kubectl get nodes
      - time helmsman -e variables.env -f k8s_common.yaml -f k8s_general.yaml -verbose -apply
    when:
      status:
        - "success"
      trigger:
        branch:
          - "master"
    depends_on:
      - "helm_lint"

  - name: notify_slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deploys
      icon_url: https://www.pngkit.com/png/full/92-920674_drone-logo-png-transparent-drone-ci-logo.png
      template: >
        {{#success build.status}}
          build {{build.number}} status: *{{build.status}}*
          build link: {{build.link}}
          build author: {{build.author}}
          build ref: {{build.ref}}
          build event: {{build.event}}
          build commit: {{build.commit}}
          build branch: {{build.branch}}
          build deploy: {{build.deployTo}}
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    when:
      status:
      - failure
      - success
    depends_on:
      - "helm_lint"
      - "helm_deploy"

trigger:
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback
