repos:
    - repo: https://github.com/tenable/terrascan
      name: terrascan-vulnerabilities
      description: 'Scanning for vulnerabilities up front'
      rev: v1.15.2
      verbose: true
      hooks:
      - id: terraform-pre-commit
        args: [ '-i helm']
