default_stages: [commit, push]
repos:
  - repo: https://github.com/tenable/terrascan
    rev: v1.15.2
    hooks:
    - id: terraform-pre-commit
      args: [ '-i helm']
      name: terrascan-vulnerabilities
      description: 'Scanning for Helm vulnerabilities up front'
      verbose: true
