image:
  name: atlassian/default-image:3

clone:
  depth: 1
options:
  max-time: 60
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: true
        script:
          - cd helm
          - git push --mirror git@github.com:DevSecOpsBr/helm-chart.git
