---
apiVersion: v1
kind: Namespace
metadata:
  name: miscellaneous
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openunison
  annotations:
    iam.amazonaws.com/permitted: ".*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  annotations:
    iam.amazonaws.com/permitted: ".*"
