{{- if .Values.admin.create }}
{{- if not (lookup "storage.loft.sh/v1" "User" "" (include "loft.admin.name" .)) }}
apiVersion: storage.loft.sh/v1
kind: User
metadata:
  name: {{ include "loft.admin.name" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install
spec:
  username: {{ .Values.admin.username }}
  {{- if .Values.admin.email }}
  email: {{ .Values.admin.email }}
  {{- end }}
  groups: ["system:masters"]
  subject: loft-admin
  {{- if ne .Values.admin.password "" }}
  passwordRef:
    secretName: loft-user-secret-admin
    secretNamespace: {{ .Release.Namespace }}
    key: password
  {{- end }}
---
{{- if .Values.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: loft-user-secret-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install
data:
  password: {{ .Values.admin.password | sha256sum | b64enc }}
{{- end }}
{{- end }}
{{- end }}
