{{ if eq .Values.enable_impersonation true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonator
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  verbs:
  - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestra-impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: impersonator
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: {{ .Release.Namespace }}
{{ end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.dashboard.namespace }}
  name: orchestra-dashboard
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - pods
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestra-dashboard
  namespace: {{ .Values.dashboard.namespace }}
subjects:
- kind: ServiceAccount
  name: openunison-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: orchestra-dashboard
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestra-certs
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orchestra-certs
subjects:
- kind: ServiceAccount
  name: openunison-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: orchestra-certs
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: openunison.tremolo.io/v1
kind: OpenUnison
metadata:
  name: orchestra
  namespace: {{ .Release.Namespace }}
spec:
  dest_secret: orchestra
  enable_activemq: false
  hosts:
  - ingress_name: openunison
    names:
    - env_var: OU_HOST
      name: {{ .Values.network.openunison_host }}
    - env_var: K8S_DASHBOARD_HOST
      name: {{ .Values.network.dashboard_host }}
    {{ if eq .Values.enable_impersonation true }}
    - env_var: K8S_API_HOST
      name: {{ .Values.network.api_server_host }}
    {{ end }}
    secret_name: ou-tls-certificate
  key_store:
    update_controller:
      image: {{ .Values.cert_update_image | default "docker.io/tremolosecurity/kubernetes-artifact-deployment:1.1.0" }}
      schedule: 0 2 * * *
      days_to_expire: 10
    key_pairs:
      create_keypair_template:
      - name: ou
        value: {{ .Values.cert_template.ou }}
      - name: o
        value: {{ .Values.cert_template.o }}
      - name: l
        value: {{ .Values.cert_template.l }}
      - name: st
        value: {{ .Values.cert_template.st }}
      - name: c
        value: {{ .Values.cert_template.c }}
      keys: 
        - create_data:
            ca_cert: true
            key_size: 2048
            server_name: openunison.openunison.svc.cluster.local
            sign_by_k8s_ca: {{ .Values.certs.use_k8s_cm }}
            subject_alternative_names: []
          import_into_ks: keypair
          name: unison-tls
        - create_data:
            ca_cert: true
            key_size: 2048
            server_name: {{ .Values.network.openunison_host }}
            sign_by_k8s_ca: false
            subject_alternative_names:
              - {{ .Values.network.dashboard_host }}
              {{ if eq .Values.enable_impersonation true }}
              - {{ .Values.network.api_server_host }}
              {{ end }} 
          import_into_ks: certificate
          name: unison-ca
          tls_secret_name: ou-tls-certificate
        - create_data:
            {{ if .Values.certs.use_k8s_cm }}
            ca_cert: false
            {{ else }}
            ca_cert: true
            {{ end }}
            key_size: 2048
            server_name: {{ .Values.dashboard.service_name }}.{{ .Values.dashboard.namespace }}.svc.cluster.local
            sign_by_k8s_ca: {{ .Values.certs.use_k8s_cm }}
            subject_alternative_names: []
            target_namespace: {{ .Values.dashboard.namespace }}
            secret_info:
              type_of_secret: Opaque
              cert_name: dashboard.crt
              key_name: dashboard.key
            delete_pods_labels:
              - {{ .Values.dashboard.label }}
          {{ if .Values.certs.use_k8s_cm  }}
          import_into_ks: "none"
          {{ else }}
          import_into_ks: "certificate"
          {{ end }}
          name: kubernetes-dashboard
          tls_secret_name: {{ .Values.dashboard.cert_name }}
          replace_if_exists: true
        - create_data:
            ca_cert: true
            key_size: 2048
            server_name: unison-saml2-rp-sig
            sign_by_k8s_ca: false
            subject_alternative_names: []
          import_into_ks: keypair
          name: unison-saml2-rp-sig
    static_keys: 
    - name: session-unison
      version: 1
    - name: lastmile-oidc
      version: 1
    
    {{ $length := len .Values.trusted_certs }}
    {{ if eq $length 0 }}
    trusted_certificates: []
    {{ else }}
    trusted_certificates: {{ range .Values.trusted_certs }}
      - name: {{ .name }}
        pem_data: {{ .pem_b64 }} {{ end }}
    {{ end }}
  non_secret_data: 
    - name: K8S_URL
      {{ if eq .Values.enable_impersonation true }}
      value: https://{{ .Values.network.api_server_host }}
      {{ else }}
      value: {{ .Values.network.k8s_url }}
      {{ end }}
    - name: SESSION_INACTIVITY_TIMEOUT_SECONDS
      value: {{ .Values.network.session_inactivity_timeout_seconds | quote }}
    - name: MYVD_CONFIG_PATH
      value: {{ .Values.myvd_config_path }}
    - name: K8S_DASHBOARD_NAMESPACE
      value: {{ .Values.dashboard.namespace }}
    - name: K8S_CLUSTER_NAME
      value: {{ .Values.k8s_cluster_name }}
    - name: K8S_IMPERSONATION
      value: {{ .Values.enable_impersonation | quote }}
    - name: PROMETHEUS_SERVICE_ACCOUNT
      value: {{ .Values.monitoring.prometheus_service_account}}
    - name: OIDC_CLIENT_ID
      value: {{ .Values.oidc.client_id }}
    - name: OIDC_IDP_AUTH_URL
      value: {{ .Values.oidc.auth_url }}
    - name: OIDC_IDP_TOKEN_URL
      value: {{ .Values.oidc.token_url }}
    - name: OIDC_IDP_LIMIT_DOMAIN
      value: {{ .Values.oidc.domain | quote }}
    - name: SUB_CLAIM
      value: {{ .Values.oidc.claims.sub }}
    - name: EMAIL_CLAIM
      value: {{ .Values.oidc.claims.email }}
    - name: GIVEN_NAME_CLAIM
      value: {{ .Values.oidc.claims.given_name }}
    - name: FAMILY_NAME_CLAIM
      value: {{ .Values.oidc.claims.family_name }}
    - name: DISPLAY_NAME_CLAIM
      value: {{ .Values.oidc.claims.display_name }}
    - name: GROUPS_CLAIM
      value: {{ .Values.oidc.claims.groups }}
    - name: OIDC_USER_IN_IDTOKEN
      value: {{ .Values.oidc.user_in_idtoken | quote}}
    - name: OIDC_IDP_USER_URL
      value: {{ .Values.oidc.userinfo_url | quote }}
    - name: OIDC_SCOPES
      value: {{ .Values.oidc.scopes }}
  openunison_network_configuration:
    activemq_dir: "/tmp/amq"
    allowed_client_names: []
    ciphers:
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
    - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
    client_auth: none
    force_to_secure: true
    open_external_port: 80
    open_port: 8080
    path_to_deployment: "/usr/local/openunison/work"
    path_to_env_file: "/etc/openunison/ou.env"
    quartz_dir: "/tmp/quartz"
    secure_external_port: 443
    secure_key_alias: unison-tls
    secure_port: 8443
  replicas: 1
  secret_data:
    - K8S_DB_SECRET
    - unisonKeystorePassword
    - OIDC_CLIENT_SECRET
  source_secret: orchestra-secrets-source
  image: {{ .Values.image }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  namespace: openunison
data:
  oidc-api-server-flags: |-
                           --oidc-issuer-url=https://{{ .Values.network.openunison_host }}/auth/idp/k8sIdp
                           --oidc-client-id=kubernetes
                           --oidc-username-claim=sub
                           --oidc-groups-claim=groups
                           --oidc-ca-file=/etc/kubernetes/pki/ou-ca.pem
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.7.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-openunison-openunison-orchestra
  name: audit2rbac:system:serviceaccount:openunison:openunison-orchestra
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    audit2rbac.liggitt.net/version: v0.7.0
  labels:
    audit2rbac.liggitt.net/generated: "true"
    audit2rbac.liggitt.net/user: system-serviceaccount-openunison-openunison-orchestra
  name: audit2rbac:system:serviceaccount:openunison:openunison-orchestra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: audit2rbac:system:serviceaccount:openunison:openunison-orchestra
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: openunison
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openunison-cr-update
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - openunison.tremolo.io
  resources:
  - openunisons
  - users
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openunison-cr-update
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openunison-cr-update
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: openunison-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-secrets
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: openunison-secrets
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: openunison-trusts-get
rules:
- apiGroups: ["openunison.tremolo.io"]
  resources: ["trusts","portalurls","orgs"]
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openunison-trusts-get
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: openunison-orchestra
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: openunison-trusts-get
  apiGroup: rbac.authorization.k8s.io