{{- if .Values.spaces.enabled }}
apiVersion: v1
kind: List
items:
{{- range $.Values.spaces.names }}
- apiVersion: cluster.loft.sh/v1
  kind: Space
  metadata:
    name: {{ . | quote }}
{{- end }}
    {{- if .Values.sleepmode.enabled }}
    annotations:
      sleepmode.loft.sh/sleep-schedule: "0 19 * * *"
      sleepmode.loft.sh/timezone: "Europe/Berlin"
      sleepmode.loft.sh/wakeup-schedule: "0 10 * * 1-5"
    {{- end }}
{{- end }}
