{{- if .Values.spaces.enabled }}
apiVersion: v1
kind: List
items:
{{- range $.Values.spaces.names }}
- apiVersion: cluster.loft.sh/v1
  kind: Space
  metadata:
    name: {{ . | quote }}
{{- end }}
{{- end }}
