apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-loadbalancers-deletion
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: protected-service-loadbalancer
    match:
      namespaces:
        - ingress
      resources:
        kinds:
        - Service
    validate:
      message: "Ops! You are not allowed to remove `Services` of type `LoadBalancer`."
      pattern:
        spec:
          type: "LoadBalancer"
      deny:
        conditions:
        - key: "{{request.operation}}"
          operator: In
          value:
          - DELETE