apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-namespace-annotations
spec:
  rules:
  - name: "Added kiam annotation"
    match:
      resources:
        kinds:
        - Namespace
    mutate:
      message: "All namespaces must have `annotations` with value `iam.amazonaws.com/permitted: \".*\"`"
      patchStrategicMerge:
        metadata:
          annotations:
            iam.amazonaws.com/permitted: ".*"

---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-label-service-type-ingress-controller
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: "Label Created"
    match:
      resources:
        kinds:
        - Service
    mutate:
      message: "Added label service-type: \"ingress-controller\"."
      patchStrategicMerge:
        (spec):
          (type): LoadBalancer
        metadata:
          labels:
            service-type: ingress-controller

---

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: who-created-this
spec:
  background: true
  rules:
  - name: "Created by:"
    match:
      resources:
        kinds:
        - Namespace
        - Deployment
        - Service
        - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            created-by: "{{request.userInfo.username}}"
