apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: release-prometheus-labels
spec:
  validationFailureAction: enforce
  rules:
  - name: release-prometheus-labels
    match:
      resources:
        kinds:
        - Deployment
        selector:
          matchLabels:
            release: prometheus
    exclude:
      resources:
        namespaces:
          - kube-system
          - kube-public
          - kube-node-lease
    validate:
      message: "label `release: prometheus` is required"
      pattern:
        metadata:
          labels:
            release: "?*"
