{{- if .Values.spaces.enabled }}
apiVersion: v1
kind: List
items:
{{- range $.Values.spaces.names }}
- apiVersion: tenancy.kiosk.sh/v1alpha1
  kind: Space
  metadata:
    name: {{ . | quote }}
{{- end }}
{{- end }}
