# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: hjacobs/kube-ops-view
  tag: 19.9.0
  pullPolicy: IfNotPresent
service:
  annotations: {}
  labels:
    environment: minikube
    system.monitoring: "prometheus"
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi
ingress:
  enabled: true
  labels:
    system.monitoring: "prometheus"
  path: /
  hostname: kubeopsview.minikube
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-opentracing: "true"
    jaeger-service-name: kubeopsview-operator
    jaeger-sampler-param: "1.0"
    jaeger-sampler-type: const
  tls: []
  ## Secrets must be manually created in the namespace
  #   - secretName: kube-ops-view.local-tls
  #     hosts:
  #       - kube-ops-view.local
rbac:
  # If true, create & use RBAC resources
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: kube-ops-view

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels:
  system.monitoring: prometheus
affinity: {}
tolerations: []

# Add securityContext
securityContext: {}

# Defaults for Redis
redis:
  enabled: false
  usePassword: false
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
