apiVersion: v1
appVersion: "0.6"
description: Validation of best practices in your Kubernetes clusters
icon: https://raw.githubusercontent.com/FairwindsOps/polaris/master/pkg/dashboard/assets/favicon-32x32.png
maintainers:
- email: robertb@fairwinds.com
  name: bobby-brennan
name: polaris
version: 0.10.2
