# Default values for kuberhealthy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  enabled: true
  name: "prometheus"
  release: prometheus
  enableScraping: true
  serviceMonitor: true
  enableAlerting: true

image:
  repository: quay.io/comcast/kuberhealthy
  tag: 2.1.0

resources:
  requests:
    cpu: 400m
    memory: 300Mi
  limits:
    cpu: 2
    memory: 1G1

tolerations:
  # change to true to tolerate and deploy to masters
  master: true

deployment:
  replicas: 3
  maxSurge: 3
  maxUnavailable: 2
  imagePullPolicy: IfNotPresent
  nodeSelector: {}
  podAnnotations: {}
  env: {}
  command:
  - /app/kuberhealthy
  # args:

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  allowPrivilegeEscalation: false

# Please remember that changing the service type to LoadBalancer
# will expose Kuberhealthy to the internet, which could cause
# error messages shown by Kuberhealthy to be exposed to the
# public internet.  It is recommended to create the service
# with ClusterIP, then to manually edit the service in order to
# securely expose the port in an appropriate way for your
# specific environment.
service:
  externalPort: 80
  type: ClusterIP
  annotations: {}

check:
  daemonset:
    enabled: true
    image:
      repository: quay.io/comcast/kh-daemonset-check
      tag: 2.0.1
    nodeSelector: {}
  deployment:
    enabled: true
    image:
      repository: quay.io/comcast/deployment-check
      tag: 1.1.1
    nodeSelector: {}
  dnsInternal:
    enabled: true
    image:
      repository: quay.io/comcast/dns-status-check
      tag: 1.0.0
    nodeSelector: {}
  podRestarts:
    enabled: true
    image:
      repository: quay.io/comcast/pod-restarts-check
      tag: 2.0.0
    nodeSelector: {}
  podStatus:
    enabled: true
    image:
      repository: quay.io/comcast/pod-status-check
      tag: 1.0.1
    nodeSelector: {}

checkReaper:
  image:
    repository: quay.io/comcast/check-reaper
    tag: 1.0.0
  nodeSelector: {}
