{{- if .Values.cluster.connect.local }}
apiVersion: config.kiosk.sh/v1alpha1
kind: Account
metadata:
  name: {{ include "loft.admin.name" . }}
  annotations:
    helm.sh/hook: pre-install
  labels:
    loft.sh/user: {{ include "loft.admin.name" . }}
spec:
  space:
    clusterRole: loft-cluster-space-default
{{- end }}