# client id: 736619635829-8ds49r2mguqm1br1ulg9794q00v0hijj.apps.googleusercontent.com
# secret: wKVYzZOVjPEuDa1LPjA3YQuS

network:
  openunison_host: "k8sou.apps.domain.int"
  dashboard_host: "k8sdb.apps.domain.int"
  api_server_host: "k8sapi.apps.domain.int"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-installer-master.tremolo.lan:6443

cert_template:
  ou: "Kubernetes"
  o: "LiveIntent GmbH"
  l: "Berlin"
  st: "Berlin"
  c: "Germany"

image: "docker.io/tremolosecurity/openunison-k8s-login-oidc:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

trusted_certs:
  - name: idp
    pem_b64: SDFGSDFGHDFHSDFGSDGSDFGDS

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

oidc:
  client_id: 736619635829-8ds49r2mguqm1br1ulg9794q00v0hijj.apps.googleusercontent.com
  auth_url: https://openunison-dev-k8s.bln.liveintent.com/auth
  token_url: https://openunison-dev-k8s.bln.liveintent.com/token
  user_in_idtoken: false
  userinfo_url: https://openunison-dev-k8s.bln.liveintent.com/token/userinfo
  domain: "liveintent.com"
  scopes: openid email profile groups
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups
